{% set version = "2.1.3" %}
{% set version_url = "2.1-3" %}

package:
  name: cunit
  version: {{ version }}

source:
  - url: https://sourceforge.net/projects/cunit/files/CUnit/{{ version_url }}/CUnit-{{ version_url }}.tar.bz2
    md5: b5f1a9f6093869c070c6e4a9450cc10c
  - path: CMakeLists.txt  # [win]

build:
  number: 1002

requirements:
  build:
    - libtool     # [unix]
    - autoconf    # [unix]
    - automake    # [unix]
    - gnuconfig   # [unix]
    - cmake       # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - ninja  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libcunit.a                        # [unix]
    - test -f ${PREFIX}/lib/libcunit${SHLIB_EXT}              # [unix]
    - if not exist %LIBRARY_INC%\cunit\Automated.h (exit 1)   # [win]
    - if not exist %LIBRARY_INC%\cunit\cUnit.h (exit 1)       # [win]
    - if not exist %LIBRARY_LIB%\cunit.lib (exit 1)        # [win]
    - if not exist %LIBRARY_BIN%\cunit.dll (exit 1)        # [win]

about:
  home: http://sourceforge.net/projects/cunit/
  license: LGPL-2.0-only
  license_file: COPYING
  summary: A Unit Testing Framework for C

extra:
  recipe-maintainers:
    - grlee77
    - wolfv
