# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VOsWvHtcb5daNmsm3VVkygl1apdVHvtbiFOxOLfjX3hHyMvHwvEdJv5AsWdMYXCU0QGE5QCsGisqe9Fko/hNjYm+c3Uqrz/2EBnG9nIt6EA+2j9ILNT2PkNPiBf7/dsiLQkZ+JfOckmm1gAM9c/klkNDfv8txxCDvBNYf7YNsiwTE5x7cbWMsso+sOKRwMPyQRmAHmvH3YVCAzpm7uitn8T+cG5YEhjyWZONQfq+cm64yn2yfKb/1eR/ApT/pXGGTPO+aPTDZCPlwajYrHN4QuRb3vfG6XCX5AbQboZyYWJw7JHsRajcgQQI89JG4kZmbdcpKrobmPN32Mt/Y/uUoOrnmvpN3rBWV/DZQei/3VRBJLxB1Vh0NBZ+RH9YbluDO3s0Sxf4dF+Hnqh6FD8ik2t7e7jYabXhpsseUAblV+fBHduXT+TO9Hmo5RKpLD3bhaNBW4MoZZ8tOyFn1i31TtkIbzlg09rIVQSZ89kV86qZT9b53BYjTV/djXYwaZTiYt0rVFzFJ1ipsc5MCHSiCT3WEHuQ49u22qrDke9xZ8hZIS/SWWJLWL9sDCmwlS6MKJ5AVWpwDdzMrDNgN10LFxFu6vy+D8mneZZGeWD8+pZCpX7s0WyRl9sIwKmJIyysfk8z00KPOrpNmA+wvGXo7H7yIXaswVjg3YiRqFNcvuo="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
