travis:
  secure:
    BINSTAR_TOKEN: VOsWvHtcb5daNmsm3VVkygl1apdVHvtbiFOxOLfjX3hHyMvHwvEdJv5AsWdMYXCU0QGE5QCsGisqe9Fko/hNjYm+c3Uqrz/2EBnG9nIt6EA+2j9ILNT2PkNPiBf7/dsiLQkZ+JfOckmm1gAM9c/klkNDfv8txxCDvBNYf7YNsiwTE5x7cbWMsso+sOKRwMPyQRmAHmvH3YVCAzpm7uitn8T+cG5YEhjyWZONQfq+cm64yn2yfKb/1eR/ApT/pXGGTPO+aPTDZCPlwajYrHN4QuRb3vfG6XCX5AbQboZyYWJw7JHsRajcgQQI89JG4kZmbdcpKrobmPN32Mt/Y/uUoOrnmvpN3rBWV/DZQei/3VRBJLxB1Vh0NBZ+RH9YbluDO3s0Sxf4dF+Hnqh6FD8ik2t7e7jYabXhpsseUAblV+fBHduXT+TO9Hmo5RKpLD3bhaNBW4MoZZ8tOyFn1i31TtkIbzlg09rIVQSZ89kV86qZT9b53BYjTV/djXYwaZTiYt0rVFzFJ1ipsc5MCHSiCT3WEHuQ49u22qrDke9xZ8hZIS/SWWJLWL9sDCmwlS6MKJ5AVWpwDdzMrDNgN10LFxFu6vy+D8mneZZGeWD8+pZCpX7s0WyRl9sIwKmJIyysfk8z00KPOrpNmA+wvGXo7H7yIXaswVjg3YiRqFNcvuo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
