travis:
  secure:
    BINSTAR_TOKEN: sIVsudXOX8O5i//BJzVjABhPCJhIvg9OuBF3E+cgxSWpvRo2AYY4j5t5giw84vTYSphQMQWiCFq1iG6a2IgLaWlm0qjd37hal0xwe7TytAo/jiu+63OVgHojQ/XIsz+r7YKg4hk9a5APcwbH8HyHIWlCm1yCaLABV1+omIoJqyqJkYDDZSuvw1HpxBDSTAvAsQiJ2Nl+Dq0RXtiYCRG6toLpJJ6LnSg8EJd17SMivhmrBiwMPbTPGLb1De0IW7HZ39rR4W1Q5JPDbPnOTmGEbeM1mC/r0BPMDgMxRXq6O4ID55oX5iNZcBek+DllYoU5veCujsUmeoiQGRxqOVN/N2LiVc5kjhxeJwH5Wf6mtPvIzCjSj4IjH6PqoMuE+7H8sxUfh7TmBJyhpDzEIaNEZBAsu1hxpSlVmkMoLGNe54SnQUPFp6DQDRWy/X2aqflXGtxMSHHtAVdNumqXdIpZ+L6DGShiKu6qlCFQlpSBn+/rMOJrEsrKasniVr2dw4/zgRhoFKLpdxvrEwgcO42WPN3K9obGtle8ZtHVI45RfzOtju588PoO79oh9ioWM0qF9rb0WYL4AIeJe+MR148j0Y5ewsQqyiiYrQMGH7/nSebEB3goaLvcRpwz2Bx6s7zYgQiUAqsXe7iNJTSG6whtLrwVhltt4PC+63RaqqJvLwc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
