travis:
  secure:
    BINSTAR_TOKEN: V3nHInk7SKXMHsLT2dbUxc4f6XJMgceaUz9XKrQ++CKyLJZFinEb7BUxsSnM57fZBcWxra5mHyGEMMTJCwsJqjBxa+LmgXJzo9M/1gz/4+86ld0wDlUnHcr9MwCO4jioNoTvRFezrt1cAwHedmb5ex8FzYlYgBJGIpImP/ARpDCpSviewDSbcM2/62MC1sR+ysVATATzbvEogJ4X+h+krv0hnzms76fKWPhzFcUZhoXSjpY3DSW+L4zrnIibLwmkZPHc4TsrKXofjoW24mmkff2nQnY8z3BPeIn0aQzCGfTZBuZHfAr2D/vQRsWOYjbzCTUnAV1zxvIVsjMPH5x6IpCYhI2lKZWRHFzyYLkuMDc2t1YQCZ3jCNLaTGmkW+gnEMqSHw3E9FP5uEUTe+kpgn9y0zqXPzovafqxD81elyMc3I07q/2975ZgrSfRwkEAfysblECIGvNMBGsKvIT1R9pZgHCepXMqdGf7B5OAgTLG+LXU1vKgvf2TPVkq7wf2YTuP9nuIR3whIIj7f/WDHGQNl12eyPCx8MBRu6lbWQQePFEv8EHZiWioPi0DO0FQ17ziAE+TjX4SHZrQUUmg2mOLOKT0Vb+BfavT0Fk1mFamE2WNP/Td4Zy5XPhKWAuUMdjx6CEWxPG6OKuGmZDycS7pL0EFCHUfxtvMwKIFtJc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
