travis:
  secure:
    BINSTAR_TOKEN: ANvw97n+a6rpgmalE+wULiZ3But3rLEJ/PLdxc91yyWTF1vNiW17FhG9BYw/tblwR0kF6hPMCThh45lqQLUhn2eyop62/j06+v8L5ISeQmDBp0PLpVeYwDm47Zdu7j+WR71INx0gFgknVzbZweV/cJrz4u7e9fSUPEXDMBew5PAgPSJ7sIeJyKeAp6V+AbV6PyKIqEGcTmlnaUBGz7xuQ4mpnDQebAzOz2oLYd8NJLm3oTcqkCNLMDD8wYf8bks9ti/z8GmCI3TI0S0G7ty9tVVLhxW87nraY9yTm1wLJxtneCt2w+x/yav/LvryCTroc51C2FzAtQEgNARrTKh9W41t3fqxpZ1bXgvg8pxdHBQ9i8V8gLBDROWQuMKdgUuKAH92cr9jEWnEkl02I3jkuin7L1k5arz91KLRqVzEvrl6I7R8wCwFPb2MQR2RP7+bKQ+JC0B19SQ53mI8Qewj+ukLb2WYCu27qU6gqx656fmM76E0BQfaedyczvM62hxvTKZS1+08SQcNgXHcpfJoRC+rmtddeW4FNw8U2FyN9z8KpNfvo9PtcdrJnkmVXx4tP+bkkOfW0cbhrts/ZplHd1cDcSUW6JAQrvhUX+bWSzlUOneWko8yccL6g2i43fiwHUJOnYaKRLz0HzPbIMEdPq+CrVTUYYV/LyCq7nRLE5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
